//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::department::Entity as Department;
pub use super::menu::Entity as Menu;
pub use super::role::Entity as Role;
pub use super::sys_role_perm::Entity as SysRolePerm;
pub use super::sys_user_role::Entity as SysUserRole;
pub use super::user::Entity as User;
