//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq,Serialize,Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub email: Option<String>,
    pub user_name: String,
    #[serde(skip_serializing)]
    pub password: String,
    pub available: bool,
    pub sex: i32,
    pub mobile: String,
    pub telephone: Option<String>,
    pub department_id: i32,
    pub last_login_time: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub created_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
